

SELECT ANIMAL_ID,NAME
FROM (SELECT o.ANIMAL_ID
     , o.NAME
     , RANK() OVER (ORDER BY DATEDIFF(o.DATETIME,i.DATETIME) DESC) AS r
FROM ANIMAL_INS AS i 
    INNER JOIN ANIMAL_OUTS AS o ON i.ANIMAL_ID = o.ANIMAL_ID 
      ) AS new
WHERE r IN (1,2)
    
