-- 코드를 입력하세요
WITH CTE AS (
SELECT RANK() OVER (ORDER BY DATEDIFF(b.DATETIME,a.DATETIME) DESC) AS ran
      ,b.ANIMAL_ID
      ,b.NAME
FROM ANIMAL_INS AS a
    INNER JOIN ANIMAL_OUTS AS b ON a.ANIMAL_ID = b.ANIMAL_ID
)

SELECT ANIMAL_ID,NAME
FROM CTE 
WHERE ran IN (1,2)
ORDER BY ran