-- 코드를 입력하세요
SELECT * FROM
(
    SELECT A.CAR_ID ,A.CAR_TYPE ,ROUND((A.DAILY_FEE - (A.DAILY_FEE /100 * C.DISCOUNT_RATE)) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR  A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID 
                                                     AND B.START_DATE <= '20221130' 
                                                     AND B.END_DATE >='20221101'
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  C ON A.CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '30일 이상'
    WHERE A.CAR_TYPE IN('SUV','세단')
    AND B.CAR_ID IS NULL
) A
WHERE A.FEE >=500000 AND A.FEE  <2000000
ORDER BY A.FEE DESC, A.CAR_TYPE ASC,A.CAR_ID DESC

# WITH car AS (
# SELECT cc.CAR_ID
#       ,cc.CAR_TYPE
#       ,cc.DAILY_FEE
# FROM CAR_RENTAL_COMPANY_CAR AS cc
#     INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh ON cc.CAR_ID = rh.CAR_ID 
# WHERE cc.CAR_TYPE IN ('세단','SUV')
#     AND rh.START_DATE >= '2022-11-01'
#     AND rh.END_DATE <= '2022-11-30' 
# )


# SELECT car.CAR_ID
#       ,car.CAR_TYPE
#       ,FLOOR((car.DAILY_FEE*dp.DISCOUNT_RATE)*30) AS FEE
# FROM car 
#     INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS dp ON car.CAR_TYPE = dp.CAR_TYPE
# WHERE FEE < 2000000 AND FEE >= 500000 AND DURATION_TYPE = '30일 이상'
# ORDER BY FEE DESC, car.CAR_TYPE ASC, car.CAR_ID DESC


#자동차 종류가 '세단' 또는 'SUV' 인 자동차 
#2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
#30일간의 대여 금액이 50만원 이상 200만원 미만