-- 코드를 입력하세요
SELECT YEAR(os.SALES_DATE) AS YEAR,
       MONTH(os.SALES_DATE) AS MONTH,
       ui.GENDER AS GENDER,
       COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO AS ui
INNER JOIN ONLINE_SALE AS os ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;
