-- 코드를 작성해주세요
WITH RECURSIVE GENERATION AS
(
  SELECT
    ID,
    PARENT_ID,
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  SELECT
    ed.ID,
    ed.PARENT_ID,
    g.GENERATION + 1 AS GENERATION
  FROM
    ECOLI_DATA AS ed
  INNER JOIN GENERATION AS g ON ed.PARENT_ID = g.ID
)

SELECT
  COUNT(g.ID) AS 'COUNT',
  g.GENERATION AS 'GENERATION'
FROM GENERATION AS g
LEFT JOIN ECOLI_DATA AS ed ON g.ID = ed.PARENT_ID
WHERE ed.PARENT_ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION;