-- 코드를 입력하세요
SELECT CAR_ID,AVAILABILITY
FROM
(
SELECT CAR_ID
      ,CASE WHEN END_DATE >= '2022-10-16' AND START_DATE <= '2022-10-16' THEN '대여중'
            WHEN END_DATE > '2022-10-16' THEN '대여 가능'
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS a
WHERE AVAILABILITY IS NOT NULL
GROUP BY CAR_ID
ORDER BY CAR_ID DESC