-- 코드를 입력하세요
# 생산일자가 2022년 5월인 식품들
# 식품 ID, 식품 이름, 총매출
# 총매출을 기준으로 내림차순 정렬, 식품 ID를 기준으로 오름차순 정렬
SELECT p.PRODUCT_ID
      ,p.PRODUCT_NAME
      ,ROUND(SUM(o.AMOUNT)*(SUM(p.PRICE)/COUNT(o.AMOUNT)),0) AS TOTAL_SALES
FROM FOOD_PRODUCT AS p
    INNER JOIN FOOD_ORDER AS o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC