-- 코드를 입력하세요
WITH CTE AS (
SELECT SHIPMENT_ID
      ,FLAVOR
      ,SUM(TOTAL_ORDER) AS sum_order
FROM FIRST_HALF
GROUP BY FLAVOR
    
UNION ALL

SELECT SHIPMENT_ID
      ,FLAVOR
      ,SUM(TOTAL_ORDER) AS sum_order
FROM JULY
GROUP BY FLAVOR
)

SELECT FLAVOR
FROM CTE
GROUP BY FLAVOR
ORDER BY SUM(sum_order) DESC
LIMIT 3