-- 코드를 입력하세요
/*
SELECT *
FROM (
SELECT PT_NAME,PT_NO,GEND_CD, AGE, TLNO
FROM PATIENT
WHERE TLNO IS NOT NULL

UNION ALL
    
SELECT PT_NAME,PT_NO,GEND_CD, AGE, "NONE" AS TLNO
FROM PATIENT
WHERE TLNO IS NULL
) AS a
WHERE AGE <= 12 AND GEND_CD = "W"
ORDER BY AGE DESC, PT_NAME ASC;*/

SELECT  PT_NAME,PT_NO,GEND_CD,AGE
        ,CASE WHEN TLNO IS NULL THEN 'NONE'
         ELSE TLNO END AS TLNO
  FROM  PATIENT
 WHERE  AGE <= '12' AND GEND_CD = 'W'
 ORDER
    BY  AGE DESC, PT_NAME
;