-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR
    ,  COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE (DATE_FORMAT(DATETIME,'%H:%i') >= '09:00'
    AND DATE_FORMAT(DATETIME,'%H:%i') < '20:00')
GROUP BY HOUR
ORDER BY HOUR