-- 코드를 입력하세요
WITH CTE AS (
    SELECT COUNT(*) AS cnt
         , MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY cnt DESC 
    LIMIT 1
)

SELECT mp.MEMBER_NAME, 
       rr.REVIEW_TEXT, 
       DATE_FORMAT(rr.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS mp
    INNER JOIN REST_REVIEW AS rr ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE mp.MEMBER_ID = (SELECT MEMBER_ID FROM CTE)
ORDER BY REVIEW_DATE,rr.REVIEW_TEXT