-- 코드를 입력하세요
WITH CTE AS (
    SELECT CAR_ID
          ,SUM(YEAR(START_DATE) = 2022 AND MONTH(START_DATE) IN (8,9,10)) AS cnt
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID 
    HAVING cnt >= 5 
)

SELECT MONTH(START_DATE) AS MONTH
      ,CAR_ID
      ,COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (CAR_ID IN (SELECT CAR_ID FROM CTE))
      AND MONTH(START_DATE) BETWEEN 8 AND 10            
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC