-- 코드를 작성해주세요
WITH year_max_table AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
      ,MAX(SIZE_OF_COLONY) AS max_size
FROM ECOLI_DATA
GROUP BY YEAR
)
SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR
      ,(b.max_size-a.SIZE_OF_COLONY) AS YEAR_DEV
      ,a.ID AS ID
FROM ECOLI_DATA AS a 
    INNER JOIN year_max_table AS b ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
    