-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS a
    INNER JOIN FISH_NAME_INFO AS b on a.FISH_TYPE = b.FISH_TYPE
WHERE b.FISH_NAME IN ('BASS', 'SNAPPER')
/*
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS a
    INNER JOIN FISH_NAME_INFO AS b on a.FISH_TYPE = b.FISH_TYPE
WHERE b.FISH_NAME = "BASS" OR b.FISH_NAME = "SNAPPER"*/