-- 코드를 입력하세요
#아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF 테이블
#아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO 테이블

SELECT FLAVOR FROM FIRST_HALF 
WHERE TOTAL_ORDER > 3000 AND FLAVOR IN (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based') 
ORDER BY TOTAL_ORDER DESC