-- 코드를 작성해주세요
SELECT hd.DEPT_ID
      ,hd.DEPT_NAME_EN
      ,ROUND(SUM(he.SAL)/COUNT(*),0) AS AVG_SAL
FROM HR_DEPARTMENT AS hd
    INNER JOIN HR_EMPLOYEES AS he ON hd.DEPT_ID = he.DEPT_ID
GROUP BY hd.DEPT_ID
ORDER BY AVG_SAL DESC